apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-host-se
spec:
  hosts:
    - google.com
  ports:
    - number: 443
      name: tls
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL