apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-se
spec:
  hosts:
    - google.com
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
      targetPort: 443
    - number: 443
      name: https-port
      protocol: HTTPS
  resolution: DNS